In [1]:
import torch

In [2]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)

In [3]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [4]:
x = torch.arange(4,dtype=torch.float32)

In [6]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [7]:
B = torch.ones(4,3,dtype=torch.float32)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [9]:
C = torch.arange(36).reshape(3,2,6)
sum_c = C.sum(axis=2,keepdims = True)
sum_c.shape

torch.Size([3, 2, 1])

In [ ]:
s 