In [2]:
import torch

In [3]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)

In [4]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [5]:
x = torch.arange(4,dtype=torch.float32)

In [6]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [7]:
B = torch.ones(4,3,dtype=torch.float32)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [9]:
C = torch.arange(36).reshape(3,2,6)
sum_c = C.sum(axis=2,keepdims = True)
sum_c.shape

torch.Size([3, 2, 1])

In [10]:
torch.cuda.is_available()

True

In [11]:
import torch
x = torch.arange(4,dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [12]:
x.requires_grad_(True)
x.grad

In [13]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [14]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
x.grad == 4*x

tensor([True, True, True, True])

In [16]:
x.grad.zero_()
# 新的函数
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [17]:
x.grad.zero_()
# 新的函数
y = x*x
# 一般对标量求导，而不是向量

In [18]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()